### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by dkav**
Add same license as was used in Google Code.

### CODE REVIEW

**Comment by dkav** [comment]
This is for the develop branch.

**Comment by johngallo** [comment]
Are the following assumptions/understandings correct about the context of this PR?  If not please clarify.  Please also discuss as appropriate.  Thanks @dkav 
* Back in the early days Brad researched all the different open source licenses and chose this one.
* He put it on the Google code repository, but it did not make the transfer to Github when the code was moved there.
* The GNU GPL was common back then, but is used less and less for X, Y, Z reasons.  (I do no know X,Y,Z).  Instead License A is the common license.  (I do not know what license A is, or if there is indeed a more common open source license currently.).
* Rather than figuring out what X,Y,Z and A are, and deciding if we should change, it would be better/easier for a few reasons to just keep the GNU GPL 2007.  
* For one, it is not a big deal since all our code is built on Esri code anyway.

**Comment by dkav** [comment]
@johngallo all I can say is the license for Linkage Mapper is the GNU GPL 2007. Google Code saved the license within its project data not in the repo itself. You can see this in the [Way Back Machine](http://web.archive.org/web/20110702121326/http://code.google.com/p/linkage-mapper/). GitHub expects the license to be saved in the repo. I think it is necessary that the license be attached to project.

As to the pros and cons of GPL, I will leave that to your own research. If you wish to change the GPL license you would most likely need my and @rgreenefl permission. Prior releases of the code would maintain the initial license either way.

**Comment by johngallo** [comment]
OK, thanks for the clarification and the confirmation.  Cool.  Merging PR now.

**Pull request merged**
