### PR TITLE
User guides and tbx updates for v3 release

### PR DESCRIPTION
**Pull request by dkav**

### CODE REVIEW

**Comment by dkav** [comment]
Forgot to add John as coauthor, so I re-pushed with updated comments. Files are unchanged from original push.

**Comment by johngallo** [comment]
Note to self in the future: The update toolbox commit is a three part commit in order to lessen the size of the repository. part 1 Darren made some changes to the .tbx in March (I think it was validation code) and got this to John. John made changes to the Linkage Priority Tool parameter names and help descriptions in June, and got it back to Darren, then Darren made some additional changes in July here. If we want to roll back to either of those intermediate versions they are here along with an intermediate LP user guide:
[intermediate products of commit.zip](https://github.com/linkagescape/linkage-mapper/files/6828467/intermediate.products.of.commit.zip)

Hoping to review the docs tomorrow night.

**Comment by dkav** [comment]
@johngallo the _tbx_ I sent to you in March included both metadata and validation changes. Validation changes were made last year. Metadata data changes were made more recently. The changes in July were metadata only.

**Comment by johngallo** [comment]
Ok, thanks for the clarification.  And the docs changes look good from what I noticed. Thanks for updating them to say that ArcPro is compatible, and witht he updated screengrabs. Glad you like all the additions I made to Linkage Priority User Guide.

**Pull request merged**
