### PR TITLE
Log file improvements – fixes #101 and #102

### LINKED ISSUE #101: List input parameters one per line in log file
Tool input parameters are currently reported in log files as:
```
Parameters:	['C:\\Users\\Sandeep\\Desktop\\Sumatra_GIS\\Linkage_Mapper_2_0_0\\Linkage_Mapper_2_0_0\\toolbox\\scripts\\lm_master.py', 'C:\\Users\\Sandeep\\Desktop\\BarrierMappingNew', 'SourceTest', 'Source', 'clipped_rast1.tif', 'true', 'true', 'Cost-Weighted & Euclidean', 'C:\\Users\\Sandeep\\Desktop\\BarrierMappingNew\\distances_SourceTest.txt', 'true', 'true', 'false', '4', 'Cost-Weighted', 'true', 'true', 'true', '200000', '#', '#', '#', '#', '#'] 
```

For clarity, list in a manner something like this:
```
Input Parameters

PROJECT DIR: C:\\Users\\Sandeep\\Desktop\\BarrierMappingNew
CORE LAYER: SourceTest
RESISTANCE LAYER: clipped_rast1.tif
...
```

### PR DESCRIPTION
**Pull request by venkanna37**
@dkav and @johngallo please go through the code and output files that will send you through the mail. I can change and send the pull request again according to your feedback.

### CODE REVIEW

**Comment by dkav** [comment]
@venkanna37 I updated your commits. Let me know if you have any questions regarding my changes or if you think there should be further revisions.

Here is the new output:
[2021_07_08_1213_Linkage Mapper.txt](https://github.com/linkagescape/linkage-mapper/files/6787578/2021_07_08_1213_Linkage.Mapper.txt)
[2021_07_08_1356_Linkage Priority.txt](https://github.com/linkagescape/linkage-mapper/files/6787584/2021_07_08_1356_Linkage.Priority.txt)
[2021_07_08_1241_Climate Linkage Mapper.txt](https://github.com/linkagescape/linkage-mapper/files/6787583/2021_07_08_1241_Climate.Linkage.Mapper.txt)
[2021_07_08_1225_Barrier mapper.txt](https://github.com/linkagescape/linkage-mapper/files/6787580/2021_07_08_1225_Barrier.mapper.txt)
[2021_07_08_1236_Circuitscape (Centrality).txt](https://github.com/linkagescape/linkage-mapper/files/6787581/2021_07_08_1236_Circuitscape.Centrality.txt)
[2021_07_08_1239_Circuitscape (Pinchpoint).txt](https://github.com/linkagescape/linkage-mapper/files/6787582/2021_07_08_1239_Circuitscape.Pinchpoint.txt)

**Review by dkav — APPROVED** [review]

**Comment by johngallo** [comment]
At the high level: looking good team!  (I have not reviewed the code
changes though, but trust that they are great.)

Idea for version 3.1 or later : add to the cores metadata: "Area of
Smallest Core":

I say this because in rare occasions the smallest core is smaller than a
resistance cell, and that crashes the model run, last I remember.  For now,
I propose we move on and get this release out!

**Comment by dkav** [comment]
@johngallo this change was not intended for the 3.0 release. Also, I think the small core issue should part of validation check or fix.

**Comment by johngallo** [comment]
As part of validation check would be great.  Or even in the error message
as a fallback. (Not sure what a validation fix would look like, but sounds
more complicated.)

I figured this was one of the commits that is a candidate for the v3.0
release.  Was hoping to discuss those candidates in our next meeting.
Regardless, since it is us getting the v 3.0 out, and all that is on your
plate right at the moment, I was figuring would be best to focus on that
release rather than this validation code idea now. Do you have a targeted
timeline for adding your changes to the .tbx and .docx in my latest pull
request?

John Gallo, Ph.D.
Senior Scientist
Conservation Biology Institute <https://consbio.org/people/staff/john-gallo>
136 SW Washington Avenue, Suite 202
Corvallis, OR 97333
Remote Office: Inglenook, CA
Phone: 707.962.9078
Twitter: @johnagallo <https://twitter.com/johnagallo>
Updates: Action Research Newsletter
<https://consbio.us9.list-manage.com/subscribe?u=3dea159e4cbe0a0ff3b43eadd&id=e3bd82fd81>

**Comment by dkav** [comment]
@johngallo you didn't give @venkanna37 time to respond before merging. Also I would prefer if you did a _rebase and merge_ commit rather than a _merge_ commit (it keeps a clear history).

**Comment by johngallo** [comment]
@dkav sorry about that. That was the only option I saw for approving the review.  I can press "revert" which starts a new pull request so @venkanna37 can compare the changes.  I'll do that unless I hear otherwise before I need to leave (11 minutes).  Regardless, I approve the review.

**Comment by dkav** [comment]
@johngallo I will take care of it.

**Comment by venkanna37** [comment]
@dkav @johngallo I thought of responding after going to lab. I will check and reply soon.

**Comment by dkav** [comment]
@johngallo Info on [rebase and merge pull requests](https://github.blog/2016-09-26-rebase-and-merge-pull-requests/).

**Comment by venkanna37** [comment]
@dkav  @johngallo I had a look at the code and log files, log files look great. As a next step, I have done some experiments on integrating Circuitscape-5 with Pinchpoint mapper and Centrality mapper. We can use CS5 as optional in those two tools, in the next week, I will send more detailed mail or post in google chat.

**Pull request merged**
