### PR TITLE
Update LP User Guide and .Style file

### PR DESCRIPTION
**Pull request by johngallo**

### CODE REVIEW

**Comment by dkav** [comment]
- I would not package the Word docs with a release, so I don't think the About doc is necessary. The word docs were originally not included in releases created with the packaging script. I would favor maintaining this approach until we got rid of using Word docs altogether.
- For the near future rather not having a Developer Documentation folder. Eventually I think the doc folder should be place elsewhere as part of larger folder reorg, at which point user guides and dev docs could be separated. I would not package the dev folder nor its contents in a release.
- What was the glitch that was the color ramps where causing? I was unaware of this issue.
- I will review the LP User Guide separately and send comments directly to you.

Also, I squashed some of your original scripts and tidied up some of the commit messages. You will need to do a force pull on the branch.

**Comment by johngallo** [comment]
Hi Darren,

i don't understand what a Force Pull is.  Is that the same thing as a Merge
Pull Request? I have that option on this or the other ones in the
screengrab below.

I think you want me to do  Merge Pull, right?

Thank,

JOhn

[image: image.png]

John Gallo, Ph.D.
Senior Scientist
Conservation Biology Institute <https://consbio.org/people/staff/john-gallo>
136 SW Washington Avenue, Suite 202
Corvallis, OR 97333
Remote Office: Inglenook, CA
Phone: 707.962.9078
Twitter: @johnagallo <https://twitter.com/johnagallo>
Updates: Action Research Newsletter
<https://consbio.us9.list-manage.com/subscribe?u=3dea159e4cbe0a0ff3b43eadd&id=e3bd82fd81>

**Comment by dkav** [comment]
@johngallo I did a rebase again to remove the insert and then the delete commits. 

Two follow up questions. First, do you really want to include the update to LP developers doc? My forthcoming changes to it will make your statements redundant. Second, I presume you want the developers folder for clarity purposes? I can live with that decision but I would prefer a shorter name.

**Comment by johngallo** [comment]
Morning Darren,

Yes, I like the folder for clarity purposes, so people do not open the
Linkage Priority Developers Guide by accident when looking for the User
guide.  I'm also hoping to instill a sense of teamwork with others,keeping
an open invitation for people to help us develop.

Fine to make it a smaller name, go with whatever you think is best.  Fine
to remove my edits to the Developer Guide if you have some coming that make
them redundant.

After you make those changes and accept the pull request, where will things
stand?

Is it that we will have a develop branch, and an ArcPro branch?

And then we ask people to test the ArcPro branch? And to use the
documentation form the develop branch? Can you cherry pick the most updated
documentation and put it into the Arc Pro branch before we share it for
testing?

Thanks,

John



John Gallo, Ph.D.
Senior Scientist
Conservation Biology Institute <https://consbio.org/people/staff/john-gallo>
136 SW Washington Avenue, Suite 202
Corvallis, OR 97333
Remote Office: Inglenook, CA
Phone: 707.962.9078
Twitter: @johnagallo <https://twitter.com/johnagallo>
Updates: Action Research Newsletter
<https://consbio.us9.list-manage.com/subscribe?u=3dea159e4cbe0a0ff3b43eadd&id=e3bd82fd81>

**Comment by johngallo** [comment]
HI Darren,

Thanks for aligning the branches that way.  It is great to have the ArcPro branch now forking off of the most recent develop commit.  I just made one commit to it to clean it up a small bit.  

I also ran it on my machine (ArcGIS 10.6.1, Win 10) for every tool, except Climate Linkage Mapper, using default settings (plus a few fill in the blank settings, like for Barrier Mapper.  All worked great!

What do you think of making this latest commit into a new Pre-Release: Linkage Mapper v3.0.0-beta.3 ? (and listing the new features/functionalities since v 2.0.0 I presume).

And/Or should we make it into a release package (with .pdfs etc)? and it can have the same name? It looks like we can publish the package on GitHub.  We can then link to it from the project webpage.

I'm leaning towards the latter being better, and announcing it on Thursday at NACCB.

Thanks!

JOhn

**Comment by johngallo** [comment]
@dkav I forgot to "mention" you on that previous post. What do you think of making this latest commit into a new Pre-Release: Linkage Mapper v3.0.0-beta.3 ?  And/Or should we make it into a release package (with .pdfs etc)? I'm leaning towards the latter. Am presenting tomorrow at 1 PM, would be great if we had at least one of them.

**Pull request merged**
